/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.example.nathandow.aoc.App
import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun appHasAGreeting() {
        val app = App()
        assertNotNull(app.greeting, "app should have a greeting")
    }
}
